### ISSUE TITLE
Homepage link error

### ISSUE THREAD

**Issue by MstrThePlague** [wepl/hrtmon#1]
On line 6 of https://github.com/wepl/hrtmon/blob/master/readme.txt the link http://dumbo.cryogen.ch/hrtmon/index.html is broken and redirects to a Wikipedia entry on Biostasis.

**Comment by wepl** [comment]
Yes, I know, but I like to keep this address in memory to the original author Alain Malek.

**Comment by MstrThePlague** [comment]
I didn't realise and thanks for explaining it.

**Comment by apolkosnik** [comment]
There's a better way, link the historical page through archive.org:

https://web.archive.org/web/19990430061857/http://dumbo.cryogen.ch/hrtmon/index.html
